### ISSUE TITLE
Issues revealed by schema validation

### ISSUE THREAD

**Issue by ProditorMagnus** [inferno8/wesnoth-Era_of_Magic#57]
https://github.com/ProditorMagnus/Ageless-for-1-14/issues/40#issuecomment-1634945286

**Comment by ProditorMagnus** [comment]
Most important out of these is that AMLA with event based abilities is not supported.

**Comment by inferno8** [comment]
Ok, so for example Desert_Salamander.cfg:52 points to `{ABILITY_EOMA_BLOODLUST 5}` which is inside `[abilities]` which is inside `[effect]` which is inside `[advancement]`. The macro contains `[event]` which is between `[/abilities](...)[+abilities]`. So the game sees `[event]` in `[effect]` and we've got (correct) `error validation: Tag [event] may not be used in [effect]`

I am guessing lack of support means this particular AMLA should not work at all and the bloodlust ability should not be added to a unit ...? But it looks like it still works.

If this needs to be fixed, I'd like to know a good solution which could keep the ability in that AMLA. Otherwise I'll have to remove it completely, I guess.

**Comment by ProditorMagnus** [comment]
Mainline has decided to move towards globally enabled events no matter if such unit exists.

**Comment by ProditorMagnus** [comment]
In case of bloodlust it works because of eoma_wesnoth_bug_3827 which loads bloodlust events.

**Comment by ProditorMagnus** [comment]
20230713 19:25:10 error validation: Tag [filter_weapon] may not be used in [chance_to_hit]
at ~add-ons/Ageless_Era/data/EoMa_data/chronoaura.cfg:27
20230713 19:23:50 error validation: Tag [movetype] may not be used in [unit_type]
at ~add-ons/Ageless_Era/units/EoMa_units/Tharis/Great_Warlock.cfg:78

These are not that important but at least chronoaura case is still here.

**Comment by inferno8** [comment]
Tried to fix some of the remaining issues. Let me know, if it works.

**Comment by ProditorMagnus** [comment]
Looks correct.
